---
collections:
  - name: containers.podman
  - name: openstack.cloud
    version: 1.8.0
  - name: git@github.com:RedHatTraining/dle.components.git
    type: git
  - name: ansible.posix
    source: https://console.redhat.com/api/automation-hub/
    #version: 1.5.4
  - name: community.general
    source: https://galaxy.ansible.com/
    #version: 6.0.1
  - name: community.crypto
    source: https://galaxy.ansible.com/
  - name: redhat_cop.ah_configuration
    source: https://galaxy.ansible.com/
  - name: ansible.controller
    source: https://console.redhat.com/api/automation-hub/
  - name: fedora.linux_system_roles
    source: https://galaxy.ansible.com/
  - name: awx.awx
    source: https://galaxy.ansible.com/
  - name: infra.ah_configuration
    source: https://galaxy.ansible.com/